name: Enforce License Compliance

on:
  pull_request:
    branches: [main, master]

jobs:
  enforce-license-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: 'Enforce License Compliance'
        uses: getsentry/action-enforce-license-compliance@bb9babc12f560cd346f94f63f3789e7cb55d9a09 # main
        with:
          fossa_api_key: ${{ secrets.FOSSA_API_KEY }}
